### ISSUE TITLE
sub-section for custom_content

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1008]
Hi @ewels ,
Would be great if content_data could be organized with sub-section as modules.
Typically, the idea would be to define a common id, so that all plots with the same ids could be organized in the same section (and display as Fastqc plots for instance).
Thanks
Nicolas

**Comment by ewels** [comment]
Ok, this took a bit of thinking but I figured out a way to make it work. Custom content can now be organised into groups!

![image](https://user-images.githubusercontent.com/465550/83161263-80be8000-a108-11ea-8f09-4fd322f2fa5e.png)

**Comment by ewels** [comment]
You should be able to try out the above example using these files: https://github.com/ewels/MultiQC_TestData/tree/master/data/custom_content/sections

Documentation on the new feature is here: https://multiqc.info/docs/#grouping-sections-and-subsections

Please have a play and let me know if you find any bugs or feature requests!

Phil

**Comment by fulaibaowang** [comment]
is it possible to have multiple plots (pngs) be grouped in one section, i tried to give them same parent_id but it did not work.
```

  unnamed-chunk-2-1:
    parent_id: count_qc
    parent_name: "Count Quality Control"
    section_name: "Count Quality Control 1"

  unnamed-chunk-2-2:
    parent_id: count_qc
    parent_name: "Count Quality Control"
    section_name: "Count Quality Control 2 "

  unnamed-chunk-2-3:
    parent_id: count_qc
    parent_name: "Count Quality Control"
    section_name: "Count Quality Control 3"

```

![Image](https://github.com/user-attachments/assets/c0fdb45b-130e-4b99-9d21-f10ed1d85504)
