### ISSUE TITLE
Allowing description to custom images

### ISSUE THREAD

**Issue by lucacozzuto** [ewels/MultiQC#1026]
**Is your feature request related to a problem? Please describe.**
When you add custom pictures you cannot add any title or description.

**Describe the solution you'd like**
I would like to consider the image in the same way we do with custom tables

**Comment by ewels** [comment]
Ok, after a bit of messing around to check what was already possible, I have now added support for this. You configure it using the `custom_data` config key, followed by the sample ID. For an image called `some_science_mqc.jpeg` that would be `some_science` - eg:

```yaml
custom_data:
    some_science:
        section_name: 'Some real science'
        description: 'This description comes from multiqc_config.yaml and helps to annotate the Custom Content image.'
```

Have a play and let me know how you get on!

Phil
