### ISSUE TITLE
New module subsection ordering has weird behaviour

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1041]
Spotted by @kohlkopf - this works:

```yaml
report_section_order:
    fastqc_status_checks:
        order: -1000
```

But this doesn't (`fastqc_status_checks` section is not moved):

```yaml
report_section_order:
    general_stats:
        order: 120
    fastqc:
        order: 110
    fastqc_status_checks:
        order: -1000
    fastq_screen:
        order: 90
    custom_read_summary_table:
        order: 80
```
