### ISSUE TITLE
Change bowtie1 color plot

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1044]
Hi,

I tried to change the bowtie1 color code following the explanation from the doc.

```yaml
custom_plot_config:
  bowtie1_alignment:
    reads_aligned:
      color: '#d84e2f'
    multimapped:
      color: '#f2e63f'
    not_aligned:
      color: '#8bbc21'
```
I'm sure about the plot name. Look at the bowtie1 code to find the key name ...
No error message ... Just that nothing changes.
Thanks
Nicolas
