### ISSUE TITLE
Force column type in table

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1049]
Hi,
I have a column in a custom table with number which actually are sample name.
So MultiQC transform them as floating values automatically.
Is there a way to force MultiQC to display them as string ?

I tried to set up the `headers` with `scale: false`, but it does not fix the issue.
Thanks
Nicolas

**Comment by ewels** [comment]
This works fine for me, I just tried this example dataset: https://github.com/ewels/MultiQC_TestData/tree/master/data/custom_content/with_config/table_headerconfig

Running in that folder but editing `multiqc_config.yaml` to add the `scale: false` config option to one of the columns:

```yaml
custom_data:
    sequencing_stats:
        id: 'sequencing_stats'
        section_name: 'Run level metrics'
        plot_type: 'table'
        pconfig:
            id: 'sequencing_stats'
            namespace: 'Sequencing stats'
        headers:
            Total reads:
                description: 'Total number of readas sequenced'
                format: '{:,.0f}'
            MBp:
                description: 'Mega base pairs'
                scale: false
            '%Q30':
                description: 'Percent of reads over Q30'
sp:
    sequencing_stats:
        fn: 'sequencing_stats.txt'
```

![image](https://user-images.githubusercontent.com/465550/68484734-26c69d80-023e-11ea-9a7f-3be7bd90bbfe.png)

Could you post your config / custom content please?

Phil

**Comment by nservant** [comment]
Sorry, maybe I was not clear.
Let say that "3238472" is your sample code (first line, MBp column).
I would like to keep it as a String, with no floating value, and no space.
Does it make sense ?
Thanks

**Comment by ewels** [comment]
Aha, I see. Sorry, yes - `scale: false` just disables the background colour bars. hmm... 🤔 

An easy hack is to change the number formatting:

```yaml
MBp:
    description: 'Mega base pairs'
    scale: false
    format: '{}'
```

That at least gets rid of the space, but apparently leaves a floating value at the end:
![image](https://user-images.githubusercontent.com/465550/68485561-d51f1280-023f-11ea-92a7-d01fe95d9181.png)

Forcing proper strings will need a new config option and a change to the custom content code, as currently it just tries to make everything a float if it can...

**Comment by ewels** [comment]
Ok.. So after a bit of experimenting I think I managed it. When parsing custom content from structured data (YAML and JSON) which has variable typing, it doesn't try to force everything to be a float. You can then do the `scale` and `format` trick I mentioned above to turn off the float typing later in the code. Then, when you get everything juuuust right, it works 🎉 

Example taken from the [test data](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/with_config/table_headerconfig/multiqc_config.yaml) and modified:

```yaml
id: 'custom_data_yaml_table'
section_name: 'Custom YAML Table'
description: 'This table is a self-contained YAML file. Hopefully the column order will be honoured.'
plot_type: 'table'
pconfig:
    id: 'custom_data_yaml_table_table'
    title: 'YAML table with ordered columns'
    min: 0
headers:
    one: {}
    two: {}
    3:
        scale: false
        format: '{}'
    4: {}
    five: {}
data:
    sample_1:
        one: 12
        two: 14
        3: '10'
        4: 7
        five: 16
    sample_2:
        one: 9
        two: 11
        3: '15'
        4: 18
        five: 21
```

![image](https://user-images.githubusercontent.com/465550/68487524-82dff080-0243-11ea-8beb-1e0f7f31ae81.png)

**Comment by ewels** [comment]
I am not going to pursue making a config option to allow this behaviour I'm afraid, as MultiQC parses numerical data in such a huge number of different places that it would be almost impossible to make it configurable everywhere.

Hopefully the above solution is enough for you - let me know how you get on! 😀

**Comment by nservant** [comment]
Thanks Phil. WIll test

**Comment by nservant** [comment]
hum ... in my case `format: '{}'` remove the space in the number but not the decimal `.0`
Here is my config
```
custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ' of sequenced data'
        plot_type: 'table'
        pconfig:
            namespace: 'stats'
            id: 'stats'
            title: 'General Statistics'
            save_file: true
            col1_header: 'Sample ID'
        headers:
            Sample_name:
              title: 'Sample Name'
              scale: false
              format: '{}'
              placement: 2000
            Number_of_reads:
              title: 'Total Reads'
              scale: 'YlGnBu'
              format: '{:,.0f}'
              placement: 4000
```
