### ISSUE TITLE
FileNotFoundError heisenbug

### ISSUE THREAD

**Issue by olgabot** [ewels/MultiQC#1162]
**Description of bug:**
Related to https://github.com/ewels/MultiQC/issues/935, I am also mysteriously getting this `FileNotFoundError: [Errno 2] No such file or directory` error seemingly randomly and came to report it.

```
Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (1)

Command executed:

  echo 1.0dev > v_pipeline.txt
  echo 20.04.1-edge > v_nextflow.txt
  fastqc --version > v_fastqc.txt
  multiqc --version > v_multiqc.txt
  fastp --version > v_fastp.txt
  diamond version > v_diamond.txt
  samtools --version > v_samtools.txt
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-predictorthologs-1.0dev/bin/multiqc", line 6, in <module>
      from multiqc.__main__ import multiqc
    File "/opt/conda/envs/nf-core-predictorthologs-1.0dev/lib/python3.7/site-packages/multiqc/__init__.py", line 15, in <module>
      from .utils import config
    File "/opt/conda/envs/nf-core-predictorthologs-1.0dev/lib/python3.7/site-packages/multiqc/utils/config.py", line 57, in <module>
      working_dir = os.getcwd()
  FileNotFoundError: [Errno 2] No such file or directory

Work dir:
  /Users/olgabot/code/nf-predictorthologs--olgabot/sourmash-search/work/3e/8eb4d13eeb4ad00a4ca9eefd959d98

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### environment.yml

<details>

```yml
# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-predictorthologs-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # TODO nf-core: Add required software dependencies here
  - bioconda::bedtools=2.29.2
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.8
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - bioconda::samtools=1.10
  - bioconda::diamond=0.9.30
  - bioconda::fastp=0.20.0
  - bioconda::bedtools=2.29.2
  - pip=20.0.2
  - conda-forge::rust=1.41.0    # Required for building sourmash from source
  - conda-forge::scikit-learn=0.22.1
  - bioconda::sourmash=3.2.2
  - conda-forge::pandas=1.0.3
  - conda-forge::tqdm=4.45.0
  - thombashi::pathvalidate=2.2.0
  - jupyter=1.0.0
  - conda-forge::s3fs=0.4.2
  - bioconda::p7zip=15.09
  - conda-forge::rsync=3.1.3
  - subread=1.6.4
  - bioawk=1.0
  - pip:
    - git+https://github.com/czbiohub/kh-tools.git@master#egg=khtools
```

</details>

### Dockerfile

<details>

```dockerfile
FROM nfcore/base:1.9
LABEL authors="Olga Botvinnik" \
      description="Docker image containing all software requirements for the nf-core/predictorthologs pipeline"

# Install the conda environment
COPY environment.yml /
RUN conda env create -f /environment.yml && conda clean -a

# Add conda installation dir to PATH (instead of doing 'conda activate')
ENV PATH /opt/conda/envs/nf-core-predictorthologs-1.0dev/bin:$PATH

# Dump the details of the installed packages to a file for posterity
RUN conda env export --name nf-core-predictorthologs-1.0dev > nf-core-predictorthologs-1.0dev.yml
```

</details>

Oddly enough, I don't get this same issue when running the comand with `bash .command.run`

```console
$ bash .command.run
fastp 0.20.0
diamond v0.9.30.131 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
```

**MultiQC Error log:**
```python
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-predictorthologs-1.0dev/bin/multiqc", line 6, in <module>
      from multiqc.__main__ import multiqc
    File "/opt/conda/envs/nf-core-predictorthologs-1.0dev/lib/python3.7/site-packages/multiqc/__init__.py", line 15, in <module>
      from .utils import config
    File "/opt/conda/envs/nf-core-predictorthologs-1.0dev/lib/python3.7/site-packages/multiqc/utils/config.py", line 57, in <module>
      working_dir = os.getcwd()
  FileNotFoundError: [Errno 2] No such file or directory
```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc --version`
 - MultiQC Version: MultiQC v1.8
 - Operating System: Whatever's on the `nfcore/base:1.9` docker image
```console
(base) root@30c33ab00c9d:/# uname -a
Linux 30c33ab00c9d 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux
```

 - Python Version:
```console
(base) root@30c33ab00c9d:/# python --version
Python 3.7.4
```

 - Method of MultiQC installation: conda
