### ISSUE TITLE
How can I change order and title image

### ISSUE THREAD

**Issue by tinatab** [ewels/MultiQC#1166]
@ewels Here you can see my config file contains 2 tables and 2 images but my report.html doesn't keep neither order nor title .
 
```yaml
output_fn_name: 'report.html'
custom_data:
    Insert_Length_image:
        file_format: '_mqc.png'
        section_name: 'Image_1'
        description: 'first image'

    base_yield_image:
        file_format: '_mqc.png'
        section_name: 'Image_2'
        description: 'second image.'

    example_files:
        file_format: 'tsv'
        section_name: 'Table_1'
        description: 'first table.'
        plot_type: 'table'

    example_files_PE:
        file_format: 'tsv'
        section_name: 'Table_2'
        description: 'second plot'
        plot_type: 'table'

sp:
    example_files:
        fn: 'table_1.tsv'
    example_files_PE:
        fn: 'table_2.tsv'
    Insert_Length:
        fn: 'hexbin_length_plot_thumb_mqc.png'
    base_yield_plot:
        fn: 'base_yield_plot_thumb_mqc.png'

custom_content:
  order:
    - Insert_Length_image
    - base_yield_image
    - example_files_PE
    - example_files                                    
```

**Comment by ewels** [comment]
Thanks @tinatab - just to check, you're missing a `'` after `'report.html` - is that just when you're pasting into the GitHub issue?

**Comment by tinatab** [comment]
@ewels  yes I forgot ' when I copied here . When I execute  the below command (with the config file that I put in issue) I don't have any error and it generate an HTML report. My tables are very well ( in the same order and title that I chose) I have also my images but only the order and title images is not as the same that i put in my config. 
Noted: I use MultiQC v1.9.dev0  

```javascript
multiqc . -f -c multiqc_config.yaml 
```

**Comment by ewels** [comment]
Hi @tinatab,

It's a bit difficult to know exactly what is wrong here and what needs fixing. Could you please send through the MultiQC report that is generated and describe what it is that you're expecting instead?

If possible it would be even better if you could also provide the files and config from above so that I can run MultiQC myself and replicate the problem.

Thanks!

Phil

**Comment by tinatab** [comment]
Hi @ewels 

I would like to add image into my report but I have 2 problems:
1) The order of sections is not as like as I set in "custom_content" (It only happens when I mix tables and/or plot with images) 
2) I set "section_name" for each image but it keeps the name of each image (filename).

Command >>   `multiqc . -f -c multiqc_config_image.yaml ` 
Version: This is MultiQC v1.9.dev0

I put files here:
[pacbio.tar.gz](https://github.com/ewels/MultiQC/files/4685101/pacbio.tar.gz)

Thanks a lot!
Tina

**Comment by ewels** [comment]
Right, it's been over two years but I'm taking a stab at this now 😁 

> 1. The order of sections is not as like as I set in "custom_content" (It only happens when I mix tables and/or plot with images

This seems to be because some of your section IDs were wrong. If I append `_plot` to the IDs (as shown in the browser address bar when clicking on the sections) and add a missing section:

```diff
4,5c4,5
<       - base_yield
<       - hexbin_length
---
>       - base_yield_plot
>       - hexbin_length_plot
7a8
>       - raw_read_length_plot
```
Giving:

```yaml
custom_content:
    order:
      - subreads_stat
      - base_yield_plot
      - hexbin_length_plot
      - loading_report
      - loading_image
      - raw_read_length_plot
```

Then the sections are ordered as expected:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/465550/189448749-80aaf56a-2b4b-403d-bdcf-7e6accc9a866.png">


> 2. I set "section_name" for each image but it keeps the name of each image (filename).

Yup, same thing - the section ID is wrong here too. Adding the `_plot` makes it work:

```yaml
custom_data:

    hexbin_length_plot:
        file_format: '_mqc.png'
        section_name: 'Hexbin_Length'
        description: 'first image.'
```

Sorry it took me so long to get to the bottom of this!

Phil
