### ISSUE TITLE
FastQC plots disabled completely when configuring table_columns_visible property

### ISSUE THREAD

**Issue by mahesh-panchal** [ewels/MultiQC#1170]
**Description of bug:**
FastQC plots are disabled when I set `FastQC: false` in the `table_columns_visible` of the config.
My understanding from the [documentation](https://multiqc.info/docs/#hiding-columns) was that this only affected the general statistics table.

config snippet:
```
table_columns_visible:
    FastQC: false
    Flash:
        combopairs: true
    QualiMap:
        avg_gc: false
        1_x_pc: true
        median_coverage: true
```

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc -c $config .` inside nextflow script.
 - MultiQC Version: MultiQC v1.8
 - Operating System: Linux
 - Python Version: Python 3.8.1
 - Method of MultiQC installation: docker image `quay.io/biocontainers/multiqc:1.8--py_2`

 **Additional context**
