### ISSUE TITLE
Picard outputs from Sentieon not parsed

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1180]
_Pasted from an email from @chrispyatt:_

I am trying to pass some Picard metrics files to MultiQC (GCBias, AlignmentStat, InsertSize, MeanQualityByCycle, Duplication, and QualDistribution) but only the Duplication metrics are being found by MultiQC.

The config file I provide contains the section below, which matches the files I am trying to use, and the multiQC log confirms that these patterns are recognised.

```yaml
sp:
    fastqc/data:
        fn: '*.stats-fastqc.txt'
    picard/alignment_metrics:
        fn: '*.AlignmentStat_metrics.txt'
        shared: true
    picard/insertsize:
        fn: '*.InsertSize_metrics.txt'
        shared: true
    picard/markdups:
        fn: '*.Duplication_metrics.txt'
        shared: true
    picard/gcbias:
        fn: '*.GCBias_metrics.txt'
        shared: true
    picard/quality_by_cycle:
        fn: '*.MeanQualityByCycle_metrics.txt'
        shared: true
    picard/quality_score_distribution:
        fn: '*.QualDistribution_metrics.txt'
        shared: true
```

The files were generated by Sentieon, but apart from the Sentieon header they seem identical in format to the Picard specs. Also the Duplication module seems to work so I think the file contents are ok. For example the GCBias file begins with:

```
#SentieonCommandLine: /usr/local/sentieon-genomics-201911/libexec/driver -t 36 -i sorted_0.bam -i sorted_1.bam -r genome/hs37d5.fa --algo GCBias --summary gc_summary.txt gc_metric.txt
ACCUMULATION_LEVEL	READS_USED	GC	WINDOWS	READ_STARTS	MEAN_BASE_QUALITY	NORMALIZED_COVERAGE	ERROR_BAR_WIDTH	SAMPLE	LIBRARY	READ_GROUP	
All Reads	ALL	0	147859	1034	19	0.182258	0.005668
```

I presume the `find_log_files` function within the modules is not returning anything, but I cannot figure out why. Is there something else in the config file that I need to specify, or some other aspect that I have overlooked? Any insight into this issue would be most appreciated.
