### ISSUE TITLE
Ability to mix custom content sections with module order

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1189]
Given quite an elaborate MultiQC report that involves using native modules as well as custom content it would be nice to have the flexibility of ordering the sections from both in a user-defined manner. For example, given the module ordering in this very tiny example [config file](https://github.com/nf-core/viralrecon/blob/11ba682ed6bca919e880c9982e731c047588fab2/assets/multiqc_config.yaml#L22) I would like to add the sections defined further down in the same [config file](https://github.com/nf-core/viralrecon/blob/11ba682ed6bca919e880c9982e731c047588fab2/assets/multiqc_config.yaml#L195) amongst the sections defined by `module_order`. Would be a boombastic feature. Over and out.

**Comment by ewels** [comment]
Is this not already possible? I'm pretty sure that the modules just get assigned and `order` as MultiQC loops through them, `+= 10` each time. So if you set `order: 15` it will end up after `fastqc` and `fastp`.

I think.

**Comment by ewels** [comment]
https://multiqc.info/docs/#order-of-module-and-module-subsection-output

> Modules and sections in the report are given a number ranging from 10 (section at bottom of report), incrementing by +10 for each section. You can change this number (eg. a very low number to always get at the bottom of the report or very high to always be at the top), or you can move a section to before or after another existing section (has no effect if the other named ID is not in the report).

You can even used named positions such as  `after: 'fastqc'` apparently. Luxury!

**Comment by drpatelh** [comment]
Ah, but what if you have multiple `fastqc` sections? 😅

**Comment by ewels** [comment]
Yeah, `after: 'fastqc-1'` I would guess, without trying it. The numeric thing just goes on order though so shouldn't care about URLs or IDs.

**Comment by ewels** [comment]
Ok, I started writing new functionality for you where you could specify a custom ID that would be appended onto the module anchor, so that you don't need to rely on the `-1` suffixes etc.

Then, I realised that you can _already_ set custom module anchors! :tada:

This works, running in the MultiQC_TestData FastQC folder:

```yaml
module_order:

    - fastqc:
        name: 'Version 7'
        anchor: 'version_7'
        info: 'FastQC reports from version 7 of FastQC'
        path_filters:
            - './v0.7.2/*'

    - fastqc:
        name: 'Version 10'
        anchor: 'version_10'
        info: 'FastQC reports from version 10 of FastQC'
        path_filters:
            - './v0.10.1/*'

    - fastqc:
        name: 'Version 11'
        anchor: 'version_11'
        info: 'FastQC reports from version 11 of FastQC'
        path_filters:
            - './v0.11.2/*'

report_section_order:
    version_7:
        before: version_11

```
