### ISSUE TITLE
Custom content being rendered as barplot even though table specified in config

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1205]
Even though I am explicitly specifying `plot_type: 'table'` in my config file one of the tsv files is being added to the report as a `bargraph`. The rest of the config associated with that section seems to be rendered as defined except for the `plot_type`. Something is being overriden somewhere it seems but I cant put my finger on it.

```
[INFO   ]  custom_content : summary_variants_metrics: Found 2 samples (bargraph)
[INFO   ]  custom_content : summary_assembly_metrics: Found 2 samples (table)
```

I have attached a minimal test example to reproduce the error below:
[test_multiqc.tar.gz](https://github.com/ewels/MultiQC/files/4689533/test_multiqc.tar.gz)

Tested on `v1.9.dev0`

**Comment by ewels** [comment]
Ok, after a bit of fiddling I got to the bottom of this. There was some functionality essentially missing from MultiQC to allow you to configure `_mqc.tsv` files from the `custom_data` configuration, which I've addressed (I _think_ it would have been fine if you'd put the config in the file headers?). There was also a bit of over-configuration going on.

Here's my working version of your config file:

```yaml
report_comment: >
    This report has been generated by the <a href="https://github.com/nf-core/viralrecon" target="_blank">nf-core/viralrecon</a>
    analysis pipeline. For information about how to interpret these results, please see the
    <a href="https://github.com/nf-core/viralrecon" target="_blank">documentation</a>.

data_format: 'yaml'

run_modules:
    - custom_content

custom_data:
    summary_variants_metrics:
        section_name: 'Variant calling metrics'
        description: 'generated by the nf-core/viralrecon pipeline'
        plot_type: 'table'
        pconfig:
            id: 'summary_variants_metrics_plot'
            table_title: 'Variant calling metrics'
            namespace: 'Variant calling metrics'
    summary_assembly_metrics:
        section_name: 'De novo assembly metrics'
        description: 'generated by the nf-core/viralrecon pipeline'
        plot_type: 'table'
        pconfig:
            id: 'summary_assembly_metrics_plot'
            table_title: 'De novo assembly metrics'
            namespace: 'De novo assembly metrics'
```

Changes:

* Removed the `sp` section - it wasn't needed as the filenames already end `_mqc.tsv`
* Removed `id` and `file_format` as they are the same as the filename, so not needed
* Changed the plot `id` so that it is unique and not the same as the section `id`
* Added `table_title` for the nice table configuration modal windows
* Removed `path_filters` as they weren't doing anything

I think that was it.. Good bug hunting though, thanks! Hopefully you'll have more luck with this now.

Phil
