### ISSUE TITLE
unable to set x axis of custom linegraph using tsv file

### ISSUE THREAD

**Issue by anoronh4** [ewels/MultiQC#1242]
**Description of unexpected behavior:**
In custom content we are able to add data from several file types (json, tsv, yaml). I am attempting to add data of several samples using tsv and i am seemingly successful with the following:
```tsv
SampleA	700650	7969	4991
SampleB	683285	7357	4688
SampleC	674329	7412	4632
```
and my config file says:
```yaml
custom_data:
    customtab:
        file_format: 'tsv'
        section_name: 'Custom Data'
        plot_type: 'linegraph'
        pconfig:
            id: 'custom_linegraph'
            title: 'Custom Data Linegraph'
sp:
    customtab:
        fn: 'testfile.tsv'
```
Multiqc infers that the x-axis for each datapoint is 1, 2, 3 . However in my case it should be 0,1,2. But using a multi-sample tsv file, it is not obvious how i'm supposed to add that information. I tried a header line where the first field is blank, but it is treated as another row in the table and is visualized as `Series0` on the linegraph (json file says`{"name":"","data": [[1,0.0],[2,1.0],[3,2.0]]}`). This is the table from that test:
```tsv
	0	1	2
SampleA	700650	7969	4991
SampleB	683285	7357	4688
SampleC	674329	7412	4632
```
The only way to customize the x-axis that I can see is to use another file format like json or yaml, but this is an unexpected limitation, since tsv files are the most common and readily available input type. 

**File that triggers the unexpected behavior:**
[testfiles.zip](https://github.com/ewels/MultiQC/files/4861792/testfiles.zip)

**MultiQC run details:**
* Command used to run MultiQC: `multiqc .`
* MultiQC Version: MultiQC v1.9
* Operating System: linux
* Python Version: Python 3.8.1
* Method of MultiQC installation: singularity container from docker://ewels/multiqc
