### ISSUE TITLE
Request: Config option to customise table column headers

### ISSUE THREAD

**Issue by stschiff** [ewels/MultiQC#1255]
I think MultiQC is awesome. But I'm struggling with the HTML Table layout a bit, specifically the very first on (called _"General Statistics"_).

1. I think it would be nice to have column widths resizable, or at least automatically size so that numbers are completely readable. If you show the table in default mode, 7-digit numbers are typically cut off.
2. The column headings are a bit confusing, since they don't show the group. So in the default setup, for example, we see multiple columns named "Seqs" or "Length" in the beginning, without clear indication what those are. Only when you click on "Configure Columns" you also see the group, like pre- vs. post-AdapterRemoval.

**Comment by apeltzer** [comment]
Just a hint on the pre- vs post-AdapterRemoval: This is a nf-core/eager output MultiQC report for example :-)

**Comment by stschiff** [comment]
Oh sorry, you mean that's specific to nf-core/eager? In that case sorry, I got confused about which repo is responsible for what.

**Comment by apeltzer** [comment]
No this is fine and should be here I guess. Just for Phil as a reference so that he knows where the pre- vs post-adapterremoval part comes from :-)

**Comment by jfy133** [comment]
For your reference for point 2 @ewels :

![image](https://user-images.githubusercontent.com/17950287/88141126-44346f80-cbf3-11ea-989e-069e1f7d9a1a.png)

I wonder if you have a customisation system for something similar how you do the table_columns_visible config section:

```
table_columns_visible:
    FastQC (pre-AdapterRemoval):
        percent_duplicates: False
        percent_gc: True
        avg_sequence_length: True
    fastp:
        pct_duplication: False
        after_filtering_gc_content: True
        pct_surviving: False
    Adapter Removal:
        aligned_total: False
        percent_aligned: True
    FastQC (post-AdapterRemoval):
        avg_sequence_length: True
        percent_duplicates: False
        total_sequences: True
        percent_gc: True
``` 

But something like this:

```
table_columns_names:
    FastQC (pre-AdapterRemoval):
        percent_duplicates: 'Pre-Proc. Duplicates'
        percent_gc: 'Pre-Proc. GC (%)'
        avg_sequence_length: ''Pre-Proc. Length'
    FastQC (post-AdapterRemoval):
        percent_duplicates: 'Post-Proc. Duplicates'
        percent_gc: 'Post-Proc. GC (%)'
        avg_sequence_length: 'Post-Proc. Length'
```
However IIRC from a previous discussion you said you wanted to ensure the column names were short for some reason?
