### ISSUE TITLE
conditional formatting according to sample categories

### ISSUE THREAD

**Issue by anoronh4** [ewels/MultiQC#1285]
**Is your feature request related to a problem? Please describe.**
multiqc allows me to indicate pass/warn/fail conditions for any column. however, the same pass/warn/fail condition might not work the same way for all samples. for example, when displaying QC on somatic and normal WGS samples, we might use a condition of `pass: - gt: 30`, which will work for normal samples but somatic samples must have at least 2x that coverage.

**Describe the solution you'd like**
Conditional formatting by sample/column combination. Might look like:
```
table_cond_formatting_rules:
    mqc-generalstats-coverage:
        tumor:
            pass:
                - gt: 30
                - eq: 30 
            fail:
                - lt: 30
        normal:
            pass:
                - gt: 60
                - eq: 60 
            fail:
                - lt: 60
```
and use a special table to specify sampleclass:
```
class_table:
  - fn: "sample_class.txt"
```
and `sample_class.txt` might look like this:
```
sampleA,normal
sampleB,tumor
```

**Describe alternatives you've considered**
i've considered a calculating 1-2 separate column to repeat/summarize the stats and apply custom conditional formatting to the new columns. For example, with 2 columns i can separate "Coverage" into "Tumor_Coverage" and "Normal_Coverage", and hide the "Coverage" column, and apply different conditions to each. Or i can calculate "Coverage_Status" as a new column that includes PASS/WARN/FAIL. however, i think something like the solution above could be more straightforward for users.
