### ISSUE TITLE
Picard CollectMultiplesMetrics plots are way different from the one in multiQC

### ISSUE THREAD

**Issue by Adrien-Evo** [ewels/MultiQC#1289]
**Description of bug:**
The Insert Metrics plots on multiQC is way different than the one from picard. This is for ATAC seq data and you can clearly see on the picard plot the "periodicity" of 200 bp corresponding to the size of nucleosoms + insert. The bump at 200bp is very small in the multiQC plot.

Plot from picard:
[SRR891276.CollectMultipleMetrics.insert_size_histogram.pdf](https://github.com/ewels/MultiQC/files/5193908/SRR891276.CollectMultipleMetrics.insert_size_histogram.pdf)

Plot from multiQC:
![image](https://user-images.githubusercontent.com/4171030/92578448-24810580-f28c-11ea-8dda-f9b5f5f5eb42.png)

I tried changing the smoothing options but this doesn't change anything.

**MultiQC Config:**

```yaml
title: "Full-ATAC pipeline"
intro_text: "Snakemake pipeline for ATAC-Seq data. Please check the Gitlab repository for more info."
report_comment: "Generated on DATE for project PROJECTNAME"


report_header_info:
    - Contact E-mail: 'adrien.foucal@gmail.com'
    - Pipeline Type: 'ATAC-Seq'

module_order:
    - MACS2_broadPeak_count
    - picard
    - preseq
    - deepTools:
        name: 'Correlation between samples'
        info: 'Spearman correlation coefficient on all aligned reads after filtering'
    - tss_plot
    - featureCounts:
        name: 'FRiP'
        info: 'Fraction of reads in peaks (FRiP)'
    - bowtie2:
        name: 'Bowtie2'
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*R[0-9]_trimmed_*fastqc.zip'
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*R[0-9]_fastqc.zip'


table_columns_visible:
    FRiP:
        Assigned: False

section_comments:
    read_distribution_profile_plot: 'Accumulated view of the distribution of sequence reads around TSS.'

custom_data:
    encode_metrics:
        plot_type: 'generalstats'
        file_format: 'tsv'
        pconfig:
            - PBC1:
                namespace: "PBC1"
                title: "PBC1"
                description: "ratio of genomic locations with EXACTLY one read pair over the genomic locations with AT LEAST one read pair"
                max: 0.8
                min: 0
                scale: 'RdYlGn'
            - PBC2:
                namespace: "PBC2"
                title: "PBC2"
                description: "ratio of genomic locations with EXACTLY one read pair over the genomic locations with EXACTLY two read pairs"
                max: 3
                min: 0
                scale: 'RdYlGn'
            - NRF:
                namespace: "NRF"
                title: "NRF"
                description: "ratio between the number of positions in the genome that uniquely mapped reads map to and the total number of uniquely mappable reads"
                max: 0.8
                min: 0
                scale: 'RdYlGn'
    mt_ratio:
        plot_type: 'generalstats'
        file_format: 'tsv'
        pconfig:
            - MT Percent:
                namespace: "MT ratio (%)"
                title: "MT ratio (%)"
                description: "mitochondrial to nuclear reads ratio (%)"
                max: 100
                min: 0
                scale: 'RdYlGn-rev'
    tss_stat:
        plot_type: 'generalstats'
        file_format: 'tsv'
        pconfig:
            - TSS:
                namespace: "TSS Enrichment"
                title: "TSS Enrichment"
                description: "Signal to noise calculation around TSS"
                max: 30
                min: 0
                scale: 'RdYlGn'
    tss_plot:
        file_format: 'tsv'
        section_name: 'TSS Coverage'
        description: 'The transcription start site profile plot (TSS) displays the number of reads that map around the transcription start site of selected genes'
        plot_type: 'linegraph'
        pconfig:
            id: 'tss_plot'
            title: 'TSS plot'
            ylab: 'Average read coverage (per million mapped reads)'
            ymax: 30
            ymin: 0

table_cond_formatting_rules:
    mqc-generalstats-tss_enrichment-TSS:
        pass:
            - gt: 10
        warn:
            - lt: 10
        fail:
            - lt: 6
    mqc-generalstats-pbc1-PBC1:
        pass:
            - gt: 0.9
        warn:
            - lt: 0.9
        fail:
            - lt: 0.7
    mqc-generalstats-pbc2-PBC2:
        pass:
            - gt: 3
        warn:
            - lt: 3
        fail:
            - lt: 1
    mqc-generalstats-nrf-NRF:
        pass:
            - gt: 0.9
        warn:
            - lt: 0.9
        fail:
            - lt: 0.7

picard_config:
    insertsize_smooth_points: 1000

sp:
    encode_metrics:
        fn: '*encodeQC.txt'
    mt_ratio:
        fn: '*mtratio.txt'
    tss_stat:
        fn: '*max.txt'
    tss_plot:
        fn: '*tss.txt'



```

**Additional context**
Here is the picard size metrics file :
[SRR891276.CollectMultipleMetrics.insert_size_metrics.txt](https://github.com/ewels/MultiQC/files/5193955/SRR891276.CollectMultipleMetrics.insert_size_metrics.txt)
