### ISSUE TITLE
Custom content ignores `path_filters`, `plot_type`, `parent_id`

### ISSUE THREAD

**Issue by chbk** [ewels/MultiQC#1337]
**Description of bug:**

Trying to separate custom bargraphs, images, and tables into sections in the MultiQC report. I want to create one section for bargraphs with a sub-section for each bargraph, one section for images with a sub-section for each image, and one section for tables with a sub-section for each table.

Doing so with the following config yaml:

```yaml
    top_modules:
      - custom_content:
          parent_id: 'bargraphs'
          plot_type: 'bargraph'
          path_filters:
            - '*_bargraph_mqc.tsv'
      - custom_content:
          parent_id: 'images'
          path_filters:
            - '*_mqc.png'
      - custom_content:
          parent_id: 'tables'
          plot_type: 'generalstats'
          path_filters:
            - '*_table_mqc.tsv'
```

The generated report duplicates every bargraph, image and table 3 times instead of separating them into sections. Furthermore the tables are transformed into bargraphs too instead of keeping them as tables.

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: `python3 -m multiqc -f --config multiqc.yaml .`
* MultiQC Version: MultiQC v1.9
* Python Version: Python 3.8.5
* Method of MultiQC installation: `pip3 install multiqc`

**Comment by ewels** [comment]
This is a very old issue, but is there a reason that you can't use [this config](https://multiqc.info/docs/#order-of-sections)? It seems to basically be designed for exactly what you're doing I think:

```yaml
custom_content:
  order:
    - first_cc_section
    - second_cc_section
```

I think that it's expected that config options you're using for `custom_content` don't work. It's not a typical module - it actually dynamically creates new module instances. You can still do the same things, they just need to be set in different places:

- `plot_type` should be within the `custom_data` config option ([docs](https://multiqc.info/docs/#data-as-part-of-multiqc-config))
- `parent_id` should use the autogenerated IDs, not `custom_content` ([docs](https://multiqc.info/docs/#configuration-1))
- I'm not sure that you can do `path_filters` for custom content, but you can set custom filename patterns to search for ([docs](https://multiqc.info/docs/#images)) which should amount to the same thing

I hope this helps and you managed to get to where you wanted. Apologies for the very very very slow response 🙏🏻 

Phil
