### ISSUE TITLE
custom content module broke error

### ISSUE THREAD

**Issue by virenar** [ewels/MultiQC#1496]
### Description of bug

I was trying to add the following custom content to multiqc report
```
custom_data:
  my_genstats:
    plot_type: "generalstats"
    pconfig:
      - col_1:
          max: 100
          min: 0
          scale: "RdYlGn"
          suffix: "%"
          format: "{:,.3f}"
      - col_2:
          min: 0
    data:
      sample_a:
        col_1: 14.32
        col_2: 1.2
      sample_b:
        col_1: 84.84
        col_2: 1.9
  my_stats:
    plot_type: "table"
    section_name: "Stats2"
    pconfig:
      - col_1:
          max: 100
          min: 0
          scale: "RdYlGn"
          suffix: "%"
          format: "{:,.3f}"
      - col_2:
          min: 0
    data:
      sample_a:
        col_1: 14.32
        col_2: 1.2
      sample_b:
        col_1: 84.84
        col_2: 1.9

```

while running with v1.11 received the following error
```
Please copy this log and report it at                                     
│ https://github.com/ewels/MultiQC/issues                                   
│ Please attach a file that triggers the error. The last file found was:    
│ None                                                                      
│                                                                           
│ Traceback (most recent call last):                                        
│   File "/usr/local/lib/python3.9/site-packages/multiqc/multiqc.py", line  
│     output = mod()                                                        
│   File "/usr/local/lib/python3.9/site-packages/multiqc/modules/custom_con 
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                      
│   File "/usr/local/lib/python3.9/site-packages/multiqc/modules/custom_con 
│     if pconfig.get("title") is None:                                      
│ AttributeError: 'list' object has no attribute 'get'    ```

### File that triggers the error

_No response_

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.11

|           multiqc | Search path : /home/ubuntu/projects/qc
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 121/121  
|    custom_content | my_genstats: Found 2 General Statistics columns
╭─────────── Oops! The 'custom_content' MultiQC module broke... ────────────╮
│ Please copy this log and report it at                                     
│ https://github.com/ewels/MultiQC/issues                                   
│ Please attach a file that triggers the error. The last file found was:    
│ None                                                                      
│                                                                           
│ Traceback (most recent call last):                                        
│   File "/usr/local/lib/python3.9/site-packages/multiqc/multiqc.py", line  
│     output = mod()                                                        
│   File "/usr/local/lib/python3.9/site-packages/multiqc/modules/custom_con 
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                      
│   File "/usr/local/lib/python3.9/site-packages/multiqc/modules/custom_con 
│     if pconfig.get("title") is None:                                      
│ AttributeError: 'list' object has no attribute 'get'                      
│                                                                           
╰───────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by ErikDanielsson** [comment]
The issue is due  `General Stats` and `tables` in being handled differently by the  `custom_content` module, see `Tricky extras/Differences between Tables and General Stats` in https://multiqc.info/docs/#custom-content

**Comment by virenar** [comment]
Thank you @ErikDanielsson! I was able to resolve the issue by updating my custom data as follows

```
custom_data:
  my_genstats:
    plot_type: "generalstats"
    pconfig:
      - col_1:
          max: 100
          min: 0
          scale: "RdYlGn"
          suffix: "%"
          format: "{:,.3f}"
      - col_2:
          min: 0
    data:
      sample_a:
        col_1: 14.32
        col_2: 1.2
      sample_b:
        col_1: 84.84
        col_2: 1.9
  my_stats:
    plot_type: "table"
    section_name: "Stats2"
    headers:
      col_1:
        max: 100
        min: 0
        scale: "RdYlGn"
        suffix: "%"
        format: "{:,.3f}"
      col_2:
        min: 0
    data:
      sample_a:
        col_1: 14.32
        col_2: 1.2
      sample_b:
        col_1: 84.84
        col_2: 1.9
```
