### ISSUE TITLE
Custom content images and fn_clean_exts

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#1502]
### Description of bug

Hi @ewels 

I found a weird bug with the images custom content.
If you add in the same config a `fn_clean_exts` scope, it seems that the image `section_name` and `description` are not longer working ... no idea why !

For instance ;
```yaml
custom_data:
    clustering_identito:
        section_name: 'Identito Clustering'
        description: ' from a list of known polymorphisms.'
sp:
  clustering_identito:
      fn: '*_mqc.png'
ignore_images: false
```
Everything is fine ...

And now ;

```yaml
clustering_identito:
        section_name: 'Identito Clustering'
        description: ' from a list of known polymorphisms.'
sp:
  clustering_identito:
      fn: '*_mqc.png'
ignore_images: false

fn_clean_exts:
    - '_bwa.log'
```

The image `section_name` and `description` are not recognized.
I tried several MultiQC versions including 1.11.

Thanks
N

### MultiQC Error log

First case:
```console
$ multiqc  . -f -c multiqcConfig2.yaml -m custom_content

  /// MultiQC 🔍 | v1.11

|           multiqc | Only using modules: custom_content
|           multiqc | Search path : /data/tmp/nservant/debug/D530_hg19/work/fa/200e9b5ef695031bc0a94802efb477
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 269/269  
|    custom_content | clustering_identito: Found 1 sample (image)
|    custom_content | summary: Found 1 sample (html)
|    custom_content | software_versions: Found 1 sample (html)
|           multiqc | Compressing plot data
|           multiqc | Deleting    : multiqc_report.html   (-f was specified)
|           multiqc | Deleting    : multiqc_data   (-f was specified)
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

With the `fn_clean_exts`

```console
$ multiqc  . -f -c multiqcConfig2.yaml -m custom_content

  /// MultiQC 🔍 | v1.11

|           multiqc | Only using modules: custom_content
|           multiqc | Search path : /data/tmp/nservant/debug/D530_hg19/work/fa/200e9b5ef695031bc0a94802efb477
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 269/269  
|    custom_content | summary: Found 1 sample (html)
|    custom_content | software_versions: Found 1 sample (html)
|    custom_content | clustering_identito_mqc.png: Found 1 sample (image)
|           multiqc | Compressing plot data
|           multiqc | Deleting    : multiqc_report.html   (-f was specified)
|           multiqc | Deleting    : multiqc_data   (-f was specified)
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```
