### ISSUE TITLE
Multiqc breaks with slash (/) in `section_name`

### ISSUE THREAD

**Issue by grst** [ewels/MultiQC#1515]
### Description of bug

When the section name contains a special char and the plot type is `table` multiqc can't create the text file with the data in the temporary directory because it looks as though the file was in a subdirectory. 

### File that triggers the error

```yaml
id: 'software_versions'
section_name: 'nf-core/rnaseq Software Versions'
section_href: 'https://github.com/nf-core/rnaseq'
plot_type: 'table'
description: 'are collected at run time from the software output.'
data:
    Workflow:
        Nextflow: 21.04.0
        nf-core/rnaseq: 3.4dev
    STAR_ALIGN:
        star: 2.6.1d
    TRIMGALORE:
        trimgalore: 0.6.6 
    SALMON_TXIMPORT:
        bioconductor-txmeta: 1.8.0
    SAMTOOLS_SORT:
        samtools: 1.12 
    STRINGTIE:
        stringtie: 2.1.7
    SALMON_QUANT:
        salmon: 1.4.0
    UCSC_BEDCLIP:
        ucsc: 377
    PICARD_MARKDUPLICATES:
        picard: 2.23.9
    SALMON_SE_GENE:
        bioconductor-summarizedexperiment: 1.20.0
    BEDTOOLS_GENOMECOV:
        bedtools: 2.30.0
```

### MultiQC Error log

```pytb
Traceback (most recent call last):                                                                                                                                │
│   File "/home/sturm/anaconda3/envs/test_multiqc/lib/python3.9/site-packages/multiqc/multiqc.py", line 624, in run                                                 │
│     output = mod()                                                                                                                                                │
│   File "/home/sturm/anaconda3/envs/test_multiqc/lib/python3.9/site-packages/multiqc/modules/custom_content/custom_content.py", line 275, in custom_module_classes │
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                                                                                                              │
│   File "/home/sturm/anaconda3/envs/test_multiqc/lib/python3.9/site-packages/multiqc/modules/custom_content/custom_content.py", line 363, in add_cc_section        │
│     self.write_data_file(mod["data"], "multiqc_{}".format(section_name.lower().replace(" ", "_")))                                                                │
│   File "/home/sturm/anaconda3/envs/test_multiqc/lib/python3.9/site-packages/multiqc/modules/base_module.py", line 467, in write_data_file                         │
│     util_functions.write_data_file(data, fn, sort_cols, data_format)                                                                                              │
│   File "/home/sturm/anaconda3/envs/test_multiqc/lib/python3.9/site-packages/multiqc/utils/util_functions.py", line 69, in write_data_file                         │
│     with io.open(os.path.join(config.data_dir, fn), "w", encoding="utf-8") as f:                                                                                  │
│ FileNotFoundError: [Errno 2] No such file or directory: '/home/sturm/tmp/tmp_ubopx22/multiqc_data/multiqc_nf-core/rnaseq_software_versions.txt'
```
