### ISSUE TITLE
MultiQC's ODGI module - How to bring all ASCII character counts of a graph into a table?

### ISSUE THREAD

**Issue by subwaystation** [ewels/MultiQC#1726]
### Description of feature

Hi there @ewels :)

When working with variation graphs, the sequences in the nodes can be nucleotides, amino acids, RNA sequences, etc.
In the end what ODGI supports are all ASCII characters. 

See this `odgi stats` output of a panproteome graph as an example:

```YAML
---
length: 986
nodes: 266
edges: 364
paths: 1392
steps: 226908
num_weakly_connected_components: 1
weakly_connected_components: 
  - component:
      id: 0
      nodes: 266
      is_acyclic: 'yes'
num_nodes_self_loops:
  total: 0
  unique: 0
A: 96
C: 4
D: 74
E: 90
F: 17
G: 69
H: 19
I: 75
K: 45
L: 81
M: 24
N: 38
P: 32
Q: 28
R: 70
S: 45
T: 55
V: 93
W: 4
Y: 27
file_size_in_bytes: 2360149
mean_links_length:
  - length:
      path: all_paths
      in_node_space: 0.611158
      in_nucleotide_space: 0.654366
      num_links_considered: 225516
      num_gap_links_not_penalized: 0
sum_of_path_node_distances:
  - distance:
      path: all_paths
      in_node_space: 1.60127
      in_nucleotide_space: 1.12001
      nodes: 226908
      nucleotides: 1218020
      num_penalties: 0
      num_penalties_different_orientation: 0
```

In https://github.com/subwaystation/MultiQC/tree/module/odgi_stats I am trying to find a way that supports the optional display not only of the number of nucleotides (A,C,T,G, N is already implemented), but of all ASCII characters. Do you see a generic way to do this?

Because I don't want to code:

```Python
        headers["G"] = {
            "title": "G",
            "description": "Number of guanine bases in the graph.",
            "scale": "RdPu",
            "format": "{:,.0f}",
            "shared_key": "nucleotides",
        }
```

For all ACSII characters. Thanks for any feedback :)

Best,
Simon
