### ISSUE TITLE
Picard metrics by Parabricks not parsed

### ISSUE THREAD

**Issue by JAMKuttan** [ewels/MultiQC#1768]
### Description of bug

I have some text files containing Picard outputs (along with some other things). I set the search patterns and content in my config, but cannot get multiqc to recognize any of the modules. 

### File that triggers the error

```yaml
title: "Parabricks Report"
subtitle: "MultiQC Analysis"
intro_text: "An Aggregation of results and quality metrics from the genomics analysis pipelines"

extra_fn_clean_exts:
  - ".mdup.txt"
  - ".alignment.txt"
  - ".base_distribution_by_cycle.pdf"
  - ".base_distribution_by_cycle.png"
  - ".base_distribution_by_cycle.txt"
  - ".coverage_metrics.txt"
  - ".gcbias.pdf"
  - ".gcbias_0.png"
  - ".gcbias_detail.txt"
  - ".gcbias_summary.txt"
  - ".insert_size.pdf"
  - ".insert_size.png"
  - ".insert_size.txt"
  - ".mean_quality_by_cycle.pdf"
  - ".mean_quality_by_cycle.png"
  - ".mean_quality_by_cycle.txt"
  - ".quality_yield.txt"
  - ".qualityscore.pdf"
  - ".qualityscore.png"
  - ".qualityscore.txt"

custom_data:
  base_distribution_by_cycle:
    section_name: "Base Distribution By Cycle"
  insert_size:
    section_name: "Insert Size"
  quality_score:
    section_name: "Quality Score"
  gc_bias:
    section_name: "GC Bias"
  mean_quality_by_cycle:
    section_name: "Mean Quality By Cycle"

sp:
  base_distribution_by_cycle:
    fn: "*.base_distribution_by_cycle.png"
  insert_size:
    fn: "*.insert_size.png"
  quality_score:
    fn: "*.qualityscore.png"
  gc_bias:
    fn: "*.gcbias_0.png"
  mean_quality_by_cycle:
    fn: "*.mean_quality_by_cycle.png"
  picard/alignment_metrics:
    fn: "*.alignment.txt"
    contents: "picard.analysis.AlignmentSummaryMetrics"
    shared: true
  picard/basedistributionbycycle:
    fn: "*.base_distribution_by_cycle.txt"
    contents: "picard.analysis.BaseDistributionByCycleMetrics"
    shared: true
  picard/gcbias:
    fn: "*.gcbias_summary.txt"
    fn: "*.gcbias_detail.txt"
    contents: "picard.analysis.GcBias*Metrics"
    shared: true
  picard/insertsize:
    fn: "*.insert_size.txt"
    contents: "picard.analysis.InsertSizeMetrics"
    shared: true
  picard/markdups:
    fn: "*.mdup.txt"
    contents: "picard.sam.DuplicationMetrics"
    shared: true
  picard/quality_yield_metrics:
    fn: "*.quality_yield.txt"
    contents: "picard.analysis.CollectQualityYieldMetrics$QualityYieldMetrics"
    shared: true
  picard/wgs_metrics:
    fn: "*.coverage_metrics.txt"
    contents: "picard.analysis.CollectWgsMetrics$WgsMetrics"
    shared: true

ignore_images: false

top_modules:
  - 'generalstats'
```

### MultiQC Error log

```console
$ multiqc -c parabricks_config.yaml .

  /// MultiQC 🔍 | v1.13

|            config | Config 'custom_logo' path not found, skipping (bantha_logo.png)
|           multiqc | Report title: Parabricks Report
|           multiqc | Search path : /data
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 54/54
|    custom_content | base_distribution_by_cycle: Found 1 sample (image)
|    custom_content | insert_size: Found 1 sample (image)
|    custom_content | quality_score: Found 1 sample (image)
|    custom_content | gc_bias: Found 1 sample (image)
|    custom_content | mean_quality_by_cycle: Found 1 sample (image)
|            picard | Found 2 MarkDuplicates reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```
