### ISSUE TITLE
Conpair concordance file not found by MultiQC

### ISSUE THREAD

**Issue by ehenrion** [ewels/MultiQC#1851]
### Description of bug

Depending on how the Conpair script `verify_concordance.py` is called (with or without the `--outfile` parameter in command line), the output is slightly different (see [here](https://github.com/nygenome/Conpair/blob/master/scripts/verify_concordance.py#L86) at lines 86 to 97)

The Conpair module of MultiQC seems to only cover the case when `--outfile` is specified in the command line : 
```yaml
conpair/concordance:
  contents: "markers (coverage per marker threshold : "
  num_lines: 3
```
Indeed, when not using the `--outfile` in command line and redirecting the output into a file instead, the pattern specified in `contents` does not match anymore. As you can see in the example file I sent, there is no space character between `threshold` and the `:` :
```
0.999
Based on 3954/7353 markers (coverage per marker threshold: 10 reads)
Minimum mappinq quality: 10
Minimum base quality: 20
```

Unfortunately I am dealing with data that have been produced using both ways... This results in some reports showing the concordance metrics and some other reports which don't show the concordance...

I have made the following change in my `search_patterns.yaml` so that the concordance file can be found : 
```yaml
conpair/concordance:
  # contents: "markers (coverage per marker threshold : "
  contents_re: '.*markers \(coverage per marker threshold\s?: .*'
  num_lines: 3
```

Now I'm wondering if this was the way to go or if there are other ways to change search patterns than having to change the "core" of multiqc, using command line parameters maybe ?

### File that triggers the error

[concordance.zip](https://github.com/ewels/MultiQC/files/10549702/concordance.zip)

### MultiQC Error log

```console
$ multiqc -f   metrics/MoHQ-CM-3-42-158703-1DT.concordance.tsv       -n ~/test/multiqc/test 


  /// MultiQC 🔍 | v1.14

|           multiqc | Search path : /lustre03/project/6007512/C3G/projects/MOH_PROCESSING/MAIN/metrics/MoHQ-CM-3-42-158703-1DT.concordance.tsv
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```
