### ISSUE TITLE
Can the color configuration of the table plot be changed directly from the yaml file

### ISSUE THREAD

**Issue by luobosi** [ewels/MultiQC#1926]
### Description of feature

Description of the problem: I am using the relevant information of the custom content to personalize some unique report content. Here I use the related software results of `checkm`. I think you may have used this software. It will generate a tab file, the sample content is as follows:

```tsv
    col1    col2    col3    col4    col5    col6    col7    col8    col9    col10   col11   col12   col13   col14
    DRR008452       g__Bacillus (UID865)    36      1200    269     79      1119    2       0       0       0       95.46   0.25    0.00
    DRR008454       g__Bacillus (UID865)    36      1200    269     114     1083    3       0       0       0       88.64   0.28    0.00
    SRR12403805     g__Bacillus (UID865)    36      1200    269     1       1197    2       0       0       0       99.81   0.25    0.00
    SRR12403810     g__Bacillus (UID865)    36      1200    269     1       1197    2       0       0       0       99.81   0.25    0.00
```

What I want is to visually display the quality of the data according to the background information of different columns, just like **the statistical table of the quast software**, so I tried the following code in yaml:

```yaml
custom_data:
   checkm_sum:
    file_format: "tsv"
    section_name: "checkm sumary"
    description: "The summary table message of checkm result, which contains completeness and contamination values."
    plot_type: 'table'
    pconfig:
     namespace: 'Summary of CheckM tab file.'
    headers:
        col1:
            title: 'Bin Id'
            description: 'unique identifier of genome bin (derived from input fasta file)'
.
.
.
        col12:
            title: 'completeness'
            description: 'estimated completeness of genome as determined from the presence/absence of marker genes and the expected collocalization of these genes'
            format: "{if val >= 90: '<span style=\"color: #BDFCC9;\">{val:.2f}</span>' else if val >= 50: '<span style=\"color: #FFF8C4;\">{val:.2f}</span>' else: '<span style=\"color: #FFC2C2;\">{val:.2f}</span>'}"
        col13:
            title: 'contamination'
            description: 'estimated contamination of genome as determined by the presence of multi-copy marker genes and the expected collocalization of these genes'
            format: '{if val <= 5: "<span style=\"color: #BDFCC9;\">{val:.2f}</span>" else if val <= 10: "<span style=\"color: #FFF8C4;\">{val:.2f}</span>" else: "<span style=\"color: #FFC2C2;\">{val:.2f}</span>"}'
        col14:
            title: 'strain heterogeneity'
            description: 'estimated strain heterogeneity as determined from the number of multi-copy marker pairs which exceed a specified amino acid identity threshold (default = 90%).'
            format: '{:,.2f}'

sp:
  checkm_sum:
    fn: "checkm.tab"
ignore_images: false
```

In my operation, it can correctly identify the data and generate the table I want, but the color matching of all columns **is the same color by default**, see the attached report PNG for details.
![test_report](https://github.com/ewels/MultiQC/assets/96641342/731c5548-520d-4872-bdfc-89a667d992ed)
I would like to know:
1. Can I change the color scheme and threshold of the relevant table **only by modifying it in the yaml file** without customizing the module?
2. If I can't implement the requirements in the yaml file, how should I modify it? Can you provide me with some reference information or tutorials? Sorry because my programming ability is very general.

Your answer will be of great help to me, I am very much looking forward to your reply.

**Comment by ewels** [comment]
Hi @luobosi,

Great question. I _think_ that it should work if you specify `scale` in your config (see the [docs](https://multiqc.info/docs/development/plots/#table-colour-scales) for available scales), eg:

```yaml
    headers:
        col1:
            title: 'Bin Id'
            description: 'unique identifier of genome bin (derived from input fasta file)'
            scale: "RdPu"
```

But with custom content I'm never totally sure! So let me know if that doesn't work and I can have a play and see if I can figure out how to do it.

Side note for the stuff you're doing with `format` - it might be possible to do with the "conditional formatting" functionality in MultiQC (see [docs](https://multiqc.info/docs/development/plots/#conditional-formatting-of-data-values)) which is designed for this. But again, not sure if it would work via custom content or not. Maybe worth a try.

If custom content doesn't work, you need to write a MultiQC module in Python. The docs / tutorial is [here](https://multiqc.info/docs/development/modules/).
