### ISSUE TITLE
Use metadata information for coloring?

### ISSUE THREAD

**Issue by lpantano** [ewels/MultiQC#200]
Hi!

I have a question that I don't know whether it can have some solution. But I had some request from @ohofmann about the options to color samples. There are cases that you can have many samples, let's say 50. And maybe you have 2/3 groups. He proposed that it would be cool to have an option to color by some information that we can add to each sample, like the group they belong or something like that. 

So there could be two approaches:

* something that we can control interactively
* something that I can add in my module. I don't know If I can give an option being the color to my graph. Maybe that is the quicker to add but I am blind here.

Of course, there is the approach to give the sample a name that have some of this information, something that you need know prior running our pipeline, or actually I can add it when creating the figures, just changing the name and add some extension that includes some of this metadata.

I realize that this maybe can not be addressed quickly, but it is one of our wishes :) Feel free to close or do whatever, since is not a real problem o super need right now.

thanks!

**Comment by ewels** [comment]
Hi @lpantano!

I'm not sure that we can incorporate this into the core program, as it requires additional metadata about samples. This would be a lot of work to do properly, and I think most users wouldn't bother to input that metadata each time they run (excluding use of MultiQC within pipelines).

You mentioned the first thing that sprang to my mind - simply appending group information to the sample name (`a-sample1`, `a-sample2`, `b-sample3`, `b-sample4` etc). That would be pretty easy to do and should work I think (though not provide an intuitive interface).

You should be possible to write something better and more integrated, but it'll require you to get your hands dirty in some JavaScript and templating. Much like the core code, the JavaScript is written in such a way to try to abstract this stuff so it's easy to manipulate. The way I would go about doing it would be to print the metadata to the page in a json object, then [load an extra javascript file](http://multiqc.info/docs/#adding-custom-css--javascript). That could work with roughly this logic:

1. Load your meta json data
2. Append HTML controls to the [toolbox](https://github.com/ewels/MultiQC/blob/master/multiqc/templates/default/toolbox.html#L33) to control new features (_eg._ dropdown boxes, check boxes and so on - depends on how you want the features to work).
3. Modify the `window.mqc_highlight_f_texts` and `window.mqc_highlight_f_cols` arrays, as done in the [current highlighting function](https://github.com/ewels/MultiQC/blob/master/multiqc/templates/default/assets/js/multiqc_toolbox.js#L341-L347).
4. Fire the `mqc_highlights` trigger as in the above function to get the plots to reload.

If you trigger the `mqc_highlights` event like this, I _think_ everything should just work. Note that adding anything to the default highlight panel afterwards would probably wipe out this highlighting, but you could even manage this if you listen to the `mqc_highlights` event as well.

There's a small amount of documentation about these JavaScript triggers [here](http://multiqc.info/docs/#custom-event-triggers).

Hope this helps! Let me know if you have any questions..

Phil

**Comment by lpantano** [comment]
Thanks for the help. I understand the amount of work. I will put this on my list for the summer where I expect to have less work. I think for now, modifying the sample names in my side should work! thanks a lot! as always.

**Comment by avilella** [comment]
Hi,

I am also after something like this here, and I thought this could be tied in together with yaml input files like the ones mentioned in this ticket:

https://github.com/ewels/MultiQC/issues/253

In the same way that we can feed in project-level information to MultiQC, maybe we could:

1. Load the meta data information for the samples in a yaml. We should agree on a key for samples, e.g. `samples` or `sample_ids`...
2. Do the pattern matching of sample ids in the yaml and the samples that MultiQC finds in the input files.
3. Once the metadata and the QC values are tied-in together, they can be displayed in the summary table and used for colouring/plotting.

E.g.:
```
report_header_info:
    - Contact E-mail: 'foo@bar.org'
    - Workflow: 'ABC-v2'
    - version: 'v-2.0.2'
    - project_name: ORGN_Run232
    - run_type: NextSeq_High_Output
    - kit_type: 2x75
    - description: ABC library, xyz experiments, final_conc:1.3pM, phix:5%
    - samples:
    - ABC44_86_1a: 
      - input_mass: 100
      - pcr_cycles: 10
    - ABC44_86_1b: 
      - input_mass: 100
      - pcr_cycles: 12
    - ABC44_86_1c: 
      - input_mass: 500
      - pcr_cycles: 8
    - ABC44_86_1d: 
      - input_mass: 500
      - pcr_cycles: 10
```
