### ISSUE TITLE
module_order merges "fastqc" data

### ISSUE THREAD

**Issue by thedam** [ewels/MultiQC#2156]
### Description of bug

I have a yaml file like this:

```
module_order:
 - cutadapt
 - trimmomatic

 - fastqc:
   name: "FastQC (final BAM)"
   anchor: "fastqc_bam"
   info: "this is my info"
   path_filters: 
    - ./BAMS/*.fastqc.zip

 - fastqc:
   name: "FastQC (raw)"
   anchor: "fastqc_raw"
   path_filters:
    - ./FASTQS/*_fastqc.zip

 - vcftools

```
In the output report, the results are merged.

My original file names are like this:
```
aaa.bam, aaa.1.fastq.gz, aaa.2.fastq.gz
ccc.bam, ccc.1.fastq.gz, ccc.2.fastq.gz
```

With above .yaml file, in the report I get two exactly the same fastqc sections, with all samples (bam and fastq) on the same plots, like:
```
aaa
aaa.1
aaa.2
ccc
ccc.1
ccc.2

```
If I remove FASTQS folder, then MultiQC uses twice whatever is in BAMS folder.

I've tried using single parenthesis in path_filters, double, with dots, without dots, but always I get the same results... 

Here is a hint what I would expect:
  /// MultiQC 🔍 | v1.17

|           multiqc | Report title: this is title
|           multiqc | Search path : /mnt/data/production/fastqs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 56/56  
|            fastqc | Found 15 reports **<-- here should be 5 reports (5 bam files)**
|            fastqc | Found 15 reports **<-- here should be 10 reports (10 fastq files)**
|           multiqc | Report      : multiqc_report.html   (overwritten)
|           multiqc | Data        : multiqc_data   (overwritten)
|           multiqc | MultiQC complete

[multiqc.log](https://github.com/ewels/MultiQC/files/13204990/multiqc.log)
[yyy_multiqc_config.yaml.txt](https://github.com/ewels/MultiQC/files/13204995/yyy_multiqc_config.yaml.txt)

### MultiQC Error log

```console
$ multiqc . --config yyy_multiqc_config.yaml -f

  /// MultiQC 🔍 | v1.17

|           multiqc | Report title: this is title
|           multiqc | Search path : /mnt/data/production/fastqs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 56/56  
|            fastqc | Found 15 reports
|            fastqc | Found 15 reports
|           multiqc | Report      : multiqc_report.html   (overwritten)
|           multiqc | Data        : multiqc_data   (overwritten)
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by tamuanand** [comment]
without info on this...it will be difficult to figure out what's going on 

```
File that triggers the error
No response
```

**Comment by thedam** [comment]
There is no errors. Program completes successfully, merges all fastqc samples, and display them twice in the report. 
The error is this "successful" merged output.

**Comment by tamuanand** [comment]
could you share those input files

**Comment by thedam** [comment]
I've found problem:

wrong ("name" starts after 3 spaces):
```
module_order:
 - fastqc:
   name: "FastQC (RAW)"
   anchor: "fastqc_raw"
   path_filters:
   - "./FASTQS/*"

 - fastqc:
   name: "FastQC (BAM)"
   anchor: "fastqc_bam"
   path_filters:
   - "./BAMS/*"

```

correct ("name" starts afters 4 spaces)
```
module_order:
 - fastqc:
    name: "FastQC (RAW)"
    anchor: "fastqc_raw"
    path_filters:
    - "./FASTQS/*"

 - fastqc:
    name: "FastQC (BAM)"
    anchor: "fastqc_bam"
    path_filters:
    - "./BAMS/*"
```
