### ISSUE TITLE
qualimap bamqc: needed files

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#220]
How does the qualimap bamqc parser detect if there is a qualimap report?
Is it by looking at the presence of `genome_results.txt` or does it require other `.html` files to be present?

I found myself that deleting everything but the `genome_results.txt` makes MultiQC (head master, pre-0.7) not find any qualimap reports...

Thx for the clarification

**Comment by ewels** [comment]
It uses a [bunch of files](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L58-L63):

```yaml
raw_data: raw_data
genome_results: genome_results.txt
coverage: coverage_histogram.txt
insert_size: insert_size_histogram.txt
genome_fraction: genome_fraction_coverage.txt
gc_dist: mapped_reads_gc-content_distribution.txt
```

Currently, it looks through the analysis directories and finds a directory called `raw_data` with a `genome_results.txt` inside, then grabs the other files after that. The method it uses is non-standard though and doesn't use the core function - this means that it misses several core functions. I currently have an issue open to rewrite it ( #210 ), so it will probably change in the near future.

Phil
