### ISSUE TITLE
Project level information

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#253]
The MultiQC_NGI plugin has a nice feature where it shows project-level information at the top of reports. This is loaded automatically from statusdb.

To make a similar thing easily accessible for other users, would be nice to have a new command line parameter to specify a file with information to display at the top. I'm thinking to have arbitrary key:value pairs, eg:

```yaml
'Contact E-mail': 'phil.ewels@scilifelab.se'
'Application Type': 'RNA-seq'
'Project Type': 'Application'
'Sequencing Platform': 'HiSeq 2500 High Output V4'
'Sequencing Setup': '2x125'
```

Probably fine to use TSV, YAML or JSON, and decide based on file extension (default TSV).

Needs the new command line option back end and new template fields for display. Probably easy to rework the MultiQC_NGI plugin to use the same framework but set the values automatically.
