### ISSUE TITLE
No handlers could be found for logger "multiqc"

### ISSUE THREAD

**Issue by royfrancis** [ewels/MultiQC#272]
Hi,
I have tried MultiQC with FastQC output and it works. Now I am trying with Skewer log files and I can't get it to work.

Running `multiqc ./path/` returns 'No results found'. So looking into the config, I found
```
skewer:
    contents: COMMAND LINE:	 skewer
```
but my log file has a full path `/path/path/skewer`. So, I created a multiqc_config.yaml in the working directory and included :

```
skewer:
    contents: COMMAND LINE:	 /path/path/skewer
```

and ran `multiqc ./path/` I get this error: `No handlers could be found for logger "multiqc"`

My log files are named 
```
a02-trimmed.log
k12-trimmed.log
m13-trimmed.log
...
```

I have tried many variations

```
sp:
        skewer:
                contents: COMMAND LINE:	 /path/path/skewer
                fn: trimmed.log

```
```
sp:
        skewer:
                fn: trimmed.log

```
```
sp:
        skewer:
                contents: null
                fn: trimmed.log

```
Also tried `multiqc -m skewer ./path/`.

They all result in the same error.

**Comment by ewels** [comment]
Hi @royfrancis,

You've been unlucky here and come into two different bugs in one go. You're completely correct that the skewer pattern match won't work for you with the `/path/path/skewer` - I need to change this to something else that will always match.

The second problem will have arrived when you started playing with the YAML file. My guess is that there's some problem with the syntax of your YAML which is triggering an error when MultiQC tries to parse it. This is caught and an error displayed, however it was done before the logging was initialised which gives you the different (and totally unhelpful) error message `No handlers could be found..`.

Hopefully you're using MultiQC v0.7, as I came across exactly the same bug last week and fixed it. So if you get a copy of the latest v0.8dev, you should get a more instructive error message saying something that there's a problem in the YAML.

My guess is that you were pretty much spot on with your first go, though it's more likely to work in single quotes:
```yaml
sp:
    skewer:
        contents: 'COMMAND LINE:  /path/path/skewer'
```

However, this is something that I should fix anyway. So I'll probably change it to `contents: 'maximum error ratio allowed (-r):'` which should work for everybody. I'll post here when I've done that, then you can remove the custom matching completely and update to v0.8dev and hopefully everything will just work for you.

Apologies for any frustration caused!

Phil
