### ISSUE TITLE
Generic module for custom output

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#300]
MultiQC relies on standardised output from tools to be able to parse and plot data. This unfortunately excludes results from any scripts that have non-standard output (eg. custom R scripts).

At the moment, we get around this problem by writing [a plugin](https://github.com/ewels/MultiQC_NGI) with modules specific to our pipelines, but I guess this is probably a little intimidating to others.

Instead, I could write a core MultiQC module that uses new MultiQC config options to define how to parse (super simple) input files:

`multiqc_config.yaml`:

``` yaml
custom_data:
  - my_custom_data_type:
      # fn: '*multiqc_scatter.csv'  # Put this in `search_patterns.yaml` / `sp`
      format: csv                   # Default: detect from extension
      section: Analysis Type        # Default: custom_data key / 'Script Output'
      title: My Results             # Default: None
      plot_type: scatter            # Default: Guess from data type (see below)
      pconfig:                      # Default: None
        title: My Scatter Plot
        xlab: X Title
        ylab: Y Title
```

`my_data_multiqc_scatter.csv`:

```
Sample-1, 1.24, 0.34
Sample-2, 8.13, 6.19
Sample-3, 2.48, 0.12
```

Input files would have to follow pretty strict formatting guidelines, but I could put examples of these into the docs.

Any thoughts from anyone? Would this be useful? Are there better ways to implement it?
