### ISSUE TITLE
Adding colors to a scatter plot

### ISSUE THREAD

**Issue by jcgrenier** [ewels/MultiQC#439]
Hi @ewels,

Thanks again for that wonderful tool! 
I'm planning to include PCA plots to my reports. In the documentation, there's no example where
we could label the points in different colors. Is there any way to do so?

Thanks a lot!!

JC

**Comment by ewels** [comment]
Hi @jcgrenier,

The easiest way to colour the points is by using the [Highlight Samples](http://multiqc.info/docs/#highlight-samples) tool within reports once it has loaded. There is a very old issue still open to make it possible to get these tools to apply by default in the report, by specifying something on the command line (#132), but this isn't possible yet and isn't a huge priority.

If you have complete control of the output, I guess it should be possible to encode the point colour though. You'd need to use YAML or JSON (as described [here](http://multiqc.info/docs/#data-as-part-of-multiqc-config)) and set `x`, `y` and also `colour` for each attribute (as shown [here](http://multiqc.info/docs/#scatter-plots)). For example, something like this:

```yaml
custom_data:
    pca_plots_data:
        id: 'mqc_pca'
        section_name: 'My PCA Data'
        description: 'This plot is generated from some PCA data'
        plot_type: 'scatter'
        pconfig:
            id: 'mqc_pca_scatter_plot'
            title: 'PCA Plot'
            ylab: 'Component 1'
            xlab: 'Component 2'
        data:
            sample_a:
                x: 12
                y: 14
                color: '#a6cee3'
            sample_b:
                x: 8
                y: 6
                color: '#a6cee3'
            sample_c:
                x: 11
                y: 5
                color: '#b2df8a'
            sample_d:
                x: 12
                y: 9
                color: '#b2df8a'
```

But I haven't tested this, so I don't really know if it will work!

I hope this helps, let me know how you get on.

Phil

**Comment by jcgrenier** [comment]
Super! Thanks a lot! 
I'll give it a try!

JC

**Comment by ewels** [comment]
To follow - yes this does work. Probably more useful is an example as a MultiQC custom content file (rather than a MultiQC config file with custom content data):

eg.: [`scatter_mqc.yaml`](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/embedded_config/test_scatter_coloured_mqc.yaml)

```yaml
id: 'mqc_pca'
section_name: 'My PCA Data'
description: 'This plot is generated from some PCA data'
plot_type: 'scatter'
pconfig:
    id: 'mqc_pca_scatter_plot'
    title: 'PCA Plot'
    ylab: 'Component 1'
    xlab: 'Component 2'
data:
    sample_a:
        x: 12
        y: 14
        color: 'red'
    sample_b:
        x: 8
        y: 6
        color: 'red'
    sample_c:
        x: 11
        y: 5
        color: 'purple'
    sample_d:
        x: 12
        y: 9
        color: 'purple'
```

Gives this:
![image](https://cloud.githubusercontent.com/assets/465550/24707704/faea47de-1a14-11e7-9567-cf3223d8dc62.png)

Phil
