### ISSUE TITLE
yPlotLines under pconfig not working

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#613]
Trying to use yPlotLines under pconfig in multiqc_config.yaml file to draw a red line at a set y value but the line does not appear on the graph.

```yaml
custom_data:
    example_coverage:
        file_format: 'tsv'
        section_name: 'Coverage Decay'
        description: 'This plot comes from files acommpanied by a mutliqc_config.yaml file for configuration'
        plot_type: 'linegraph'
        pconfig:
            id: 'coverage_lineplot'
            title: 'Coverage Decay'
            ylab: 'X Coverage'
            ymax: 100
            ymin: 0
            yPlotLines: [{'color': '#FF0000','value': 80}]

sp:
    example_coverage:
        fn: 'coverage_*'

```

Perhaps the syntax is not right?

* **Command used to run MultiQC**
`multiqc . -f`
* **MultiQC Version:**
MultiQC v1.1
* **Operating System:**
 (Red Hat 4.8.5-11)] on linux
* **Python Version:**
Python 3.4.5 (default, May 29 2017, 15:17:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
* **Method of MultiQC installation:**
 Donno
