### ISSUE TITLE
Improving module order for custom data 

### ISSUE THREAD

**Issue by lucacozzuto** [ewels/MultiQC#616]
I tried to mix custom and standard modules but the custom data goes always at the top.
Example:

```yaml
module_order:
 - fastqc:
        name: 'FastQC'
 - qualimap
 - bowtie2
 - peakcall # custom
 - tools-html # custom
```

**Comment by ewels** [comment]
`module_order` changes the sequence that the MultiQC modules are executed, not the order of sections in the report. Custom inputs are always handled by the `custom_content` module, so I guess you'd need the following instead:

```yaml
module_order:
 - fastqc:
        name: 'FastQC'
 - qualimap
 - bowtie2
 - custom_content
```

Alternatively, you can also customise the order of report sections (separate from when modules run in MultiQC). See [the docs](http://multiqc.info/docs/#order-of-sections).  eg.:

```yaml
module_order:
 - fastqc
 - qualimap
 - bowtie2
report_section_order:
 - peakcall:
        order: -100
 - tools-html:
        order: -200
```
Note that this is quite new and may still be in the unreleased v1.3dev version.

Phil
