### ISSUE TITLE
Automatic colouring for PASS/FAIL values in custom tables

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#646]
New feature request:

Is there an easy way to do conditional formatting in the report? For instance, if I'm importing a custom table with PASS/FAIL values for all samples in the run, could I highlight automatically the "FAIL" ones in red and "PASS" ones in green?

Your reply in Gitter:
The first would be fairly easy to do by supplying HTML as the contents of the cell though (and turning off the automatic formatting).
eg. `<span class=“label label-success”>Pass</span>` and `<span class=“label label-danger”>Fail</span>`
I could add in some functionality to do this automatically too quite easily - maybe make a new issue for that for me?

Many thanks in advance!

**Comment by ewels** [comment]
Hi @RoxaneLS,

I've just added a new feature to do this. The default config is set up to highlight any table cells that say `PASS` or `FAIL` without any additional configuration, so if you download the latest development version it should just work.

Let me know how it goes!

Phil

**Comment by RoxaneLS** [comment]
Thanks! I'm back from holidays, will try it out and let you know. Cheers

**Comment by RoxaneLS** [comment]
Hi Phil, I've tried it using v1.4.dev0 but the colouring did not work. I'm reading a custom table, see one example attached.

This is the relevant part in my config file:
```
custom_data:
    stats_summary:
        id: 'stats_summary'
        section_name: 'Stats Summary Table'
        plot_type: 'table'
        pconfig:
            id: 'stats_summary'
            #title: 'Stats Summary Table'
sp:
    stats_summary:
        fn: '*stats_summary.txt'
```

Am I missing something?
Cheers,
Roxane

[08060327.stats_summary.txt](https://github.com/ewels/MultiQC/files/1613993/08060327.stats_summary.txt)
