### ISSUE TITLE
Conflicting conditional formatting gives double-labelled values

### ISSUE THREAD

**Issue by aledj2** [ewels/MultiQC#663]
Hi,

The sex check column in peddy returns true if a sex error is seen and false if no sex error is seen (sex is as expected). Therefore because errors are True these are a in a nice green box where as  those which pass the test are red (==False) are in a red box.

I tried changing `config.yaml` using:
```yaml
table_cond_formatting_rules:
    mqc-generalstats-error_sex_check:
        fail:
            - s_eq: 'true'
        pass:
            - s_eq: 'false' 
```

However this resulted in both green and red boxes around each value

To get around this I've changed the peddy module so it swaps true and false to get the colours correct, and removed the code from the `config.yaml` but not sure if this is the best approach?
