### ISSUE TITLE
Multiply-run modules don't appear general stats table after v1.3

### ISSUE THREAD

**Issue by daler** [ewels/MultiQC#715]
To get multiple FastQC runs to show up in the General Stats table, I had followed the docs at http://multiqc.info/docs/#running-modules-multiple-times.  It had worked as expected in v1.3, with columns for each separate run of the module. However I found it does not actually work in v1.4 or v1.5. Specifically, in later versions the last module overwrites the others in the General Stats table. 

It seems to be [this relatively new block](https://github.com/ewels/MultiQC/blob/5931f7ea24061410e4578a71da54be5c19ea47fa/scripts/multiqc#L530) causing the issue, since commenting that out in master branch solves the problem. I'm afraid I don't understand the `'rid'` business enough to propose a fix though.

Example config:

```yaml
module_order:
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*.cutadapt.fastq.gz_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*.fastq.gz_fastqc.zip'
```
