### ISSUE TITLE
Sort rows alphabetically in custom tables 

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#762]
Hi Phil,
it would be great if rows (i.e. sample names) could be sorted alphabetically in custom tables, just like they are in the General Stats table. Currently users have to click on the "Sample" header of every single table to sort them.

Here is our chat in Gitter for your reference:
> **Roxane Legaie @RoxaneLS 15:13**
> Also I think I found a small bug.. The rows in my custom tables are not alphabetically sorted (which means users have to sort every single table in their QC reports). I looked in the doc and found that I can specify `sortRows: TRUE ` in the config file but it doesn't seem to work.
Interestingly they are always sorted alphabetically in the General Stats table which comes from fastqc and bcl2fastq modules..
>
> **Phil Ewels @ewels 16:20**
> Yes, it should probably sort by default with an option to disable this.

**Description of bug:**
Rows in custom tables are not ordered alphabetically by default (although input data for multiqc is sorted).

* **File that triggers the error:**
[run_concordance.txt](https://github.com/ewels/MultiQC/files/2011715/run_concordance.txt)

* **Command used to run MultiQC**
    * `multiqc .`
    * `multiqc ${MULTIQCDIR} -f -o $MULTIQCDIR -n multiqc_report -c ${multiqc_config}`

[multiqc_config.yaml.txt](https://github.com/ewels/MultiQC/files/2011720/multiqc_config.yaml.txt)

* **MultiQC Version:**
    * MultiQC v1.4. Also tried with v1.6.dev0 and same issue.
* **Operating System:**
    * Linux
* **Python Version:**
    * Python 2.7
* **Method of MultiQC installation:**
    * pip or conda

**Comment by ewels** [comment]
Hi @RoxaneLS,

I've just had a look at the code and found the offending section. It should be fixed in the latest development version - thanks for letting me know!

Note that your test data is of concordance values. You're using a table here, but it looks perfect for a heatmap. See example files: [run_concordance.zip](https://github.com/ewels/MultiQC/files/2020440/run_concordance.zip)

![image](https://user-images.githubusercontent.com/465550/40280740-3fdc7fe8-5c58-11e8-8dd0-c56d62183b7e.png)

(Basically just switched `plot_type: 'table'` for `plot_type: 'heatmap'`).

Phil

**Comment by RoxaneLS** [comment]
Rowe sorting works well for me in latest dev version.. any idea when this will be available for release?

Heatmap looks great, they LOVE it!!

**Comment by ewels** [comment]
> Row sorting works well for me in latest dev version.. any idea when this will be available for release?

Great! Thanks for letting me know. Difficult to guess when the next release will be, though the new features are starting to add up so it shouldn't be too long. Probably in the order of a few weeks.

> Heatmap looks great, they LOVE it!!

Great! 😁

**Comment by etvedte** [comment]
How can you disable automatic sorting? I tried the following, which didn't work:
```
custom_data:
    feature_counts:
        section_name: 'Feature counts'
        plot_type: 'table'
        pconfig:
            id: feature_counts
            namespace: 'feature counts'
        headers:
            Feature:
                description: 'Description of feature'
            Value:
                description: 'Count of features'
        sortRows: False
```
Note this is indeed custom data, not output from featureCounts that would be supported by that specific module
