### ISSUE TITLE
Run modules twice and compare

### ISSUE THREAD

**Issue by gadepallivs** [ewels/MultiQC#764]
I setup a config file to run hisat2 twice. Just to compare the summary stats from 2 different version of a reference genome. I think the prior one is overwriting the other. Would it be possible to run a module twice, but have plots for both to visually compare them ? 
Similarly, would like to run other module to compare differences in output with changing parameters. Is this possible ? Appreciate your help. Thank you for the wonderful report summarizer. 

 here is how I had my config file
```yaml
  - hisat2:
      name: 'hisat2(hg19)'     
      path_filters:
         - '/path/to/hisat/summary/output/hg19/'  
   - hisat2:
      name: 'hisat2(gc38)'
      path_filters:
         - '/path/to/hisat/summary/output/gc38/'
```
