### ISSUE TITLE
Ordering of reports doesn't seem to work (used to work)

### ISSUE THREAD

**Issue by mohammedkhalfan** [ewels/MultiQC#781]
**Description of bug:**
Ordering of reports doesn't seem to work. I have 2 reports, `run_stats` and `demux_report`. Ordering used to work on an older dev version of MultiQC. 

Here is my config (file is called `mqc_config.yaml`):
```yaml
report_section_order:
  demux_report:
    after: 'run_stats'
```
Here is an old config which used to work with an older dev version of MultiQC:
```yaml
custom_content:
  order:
    - run_stats
    - demux_report
```

- _Command used to run MultiQC:_ `multiqc -c /path/to/mqc_config.yaml -f .`
- _MultiQC Version:_ I have tried with version 1.0.dev0 and version 1.5
- _Operating System:_ CentOS Linux release 7.3.1611 (Core)
- _Python Version:_ 2.7.12

Thank you!
