### ISSUE TITLE
Specify which table/plot from pre-defined modules

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#797]
Hi Phil,
could you pls implement a solution to allow the users to specify which table/plot they want from pre-defined modules such as GATK VariantEval, in the back-end.

For instance, I like what it does with the _Variant Count_ graph, but I don't want the _Compare Overlap_ table.

It would be great if we could define it in the config file, similarly to what we do for the General Stats table:

```yaml
table_columns_visible:
    GATK VariantEval:
        known_titv: False
        novel_titv: False
```

Thanks a lot!
