### ISSUE TITLE
Question on custom content

### ISSUE THREAD

**Issue by nservant** [ewels/MultiQC#839]
Hi @ewels 
Sorry to disturb you again. I have a short question about the custom content.
Here is the context ; 
I would like to show a new table (frequency of a few SNPs) in the MultiQC report. I therefore generated a custom content ;

```yaml
custom_data:
    my_polym:
        file_format: 'tsv'
        section_name: 'Polymorphism Metrics'
        description: ' on a list of know variants'
        plot_type: 'table'
        pconfig:
            title: 'Polymorphisms'
            id: 'polym'
            format: '{:,.0f}'

sp:
   my_polym:
       fn: '*.polym.g.tsv'
```
It works pretty well. However, the final users would like to be able to export this table from the report.
I looked at the ToolBox, but it seems that only data from plots (not table ?) can be exported ? I also check in the multiqc_data but my table is not there.
Is there any way to export a table ? something to add in the custom content ?
Many thanks for your help
best

**Comment by ewels** [comment]
Hi @nservant,

No problem - from memory, there should be a "copy" button next to all tables to copy the contents to the clipboard. The toolbox doesn't have any feature for this as you say - this would be easy to add though, it's a nice idea! Feel free to create a new issue about this.

You can tell MultiQC to save the table contents to a file by specifying the `save_file` config parameter (see [docs](http://multiqc.info/docs/#creating-a-table)). eg:

```yaml
        pconfig:
            title: 'Polymorphisms'
            id: 'polym'
            format: '{:,.0f}'
            save_file: true
```

I hope that helps! Let me know if you have troubles.

Phil
